Assignment submission
TheRightQuestion/course-0-assignment-0 pull request #5
Opened 2020-04-11 07:43 UTC by vaibhav-trq

2020-04-13 04:05 UTC, closed without merging

2020-04-15 21:59 UTC, hellovai approved these changes
This looks great! Nice job.

2020-04-15 22:00 UTC, jackarendt approved these changes
This looks great! Nice job.

2020-04-15 22:15 UTC, hellovai requested changes
Please address all of the comments.

2020-04-15 22:16 UTC, vaibhav-trq reviewed
Adding new comments.

2020-04-15 22:16 UTC, hellovai approved these changes
This looks great! Nice job.

2020-05-02 08:43 UTC, hellovai requested changes
Please address all of the comments.

2020-05-02 08:43 UTC, vaibhav-trq reviewed
Adding new comments.

2020-05-02 08:43 UTC, hellovai approved these changes
This looks great! Nice job.

2020-05-02 08:49 UTC, hellovai requested changes
Please address all of the comments.

2020-05-02 08:51 UTC, vaibhav-trq reviewed
Adding new comments.

2020-05-02 08:51 UTC, hellovai approved these changes
This looks great! Nice job.

2020-05-04 08:47 UTC, hellovai requested changes
Please address all of the comments.

2020-05-04 08:47 UTC, hellovai commented on fix-code-0/main.cpp
> +  cout << "Hello World!" << endl;
Add some spacing between here!

2020-05-04 08:50 UTC, hellovai requested changes
Please address all of the comments.

2020-05-04 08:50 UTC, hellovai commented on fix-code-0/main.cpp
>  int main() {
fads

2020-05-04 08:51 UTC, hellovai requested changes
Please address all of the comments.

2020-05-04 08:51 UTC, hellovai commented on fix-code-0/main.cpp
> +  cout << "Hello World!" << endl;
fsadf

2020-05-04 08:52 UTC, hellovai requested changes
Please address all of the comments.

2020-05-04 08:52 UTC, hellovai commented on fix-code-0/main.cpp
> +  cout << "Hello World!" << endl;
fsadf

2020-05-04 08:52 UTC, hellovai requested changes
Please address all of the comments.

2020-05-04 08:52 UTC, hellovai commented on fix-code-0/main.cpp
> +  cout << "Hello World!" << endl;
fsadf

2020-05-04 08:53 UTC, hellovai requested changes
Please address all of the comments.

2020-05-04 08:53 UTC, hellovai commented on fix-code-0/main.cpp
>  }
afsdf

2020-05-04 08:54 UTC, hellovai requested changes
Please address all of the comments.

2020-05-04 08:54 UTC, hellovai commented on fix-code-0/main.cpp
>  }
afsdf

2020-05-05 02:09 UTC, vaibhav-trq reviewed
Adding new comments.

2020-05-05 02:09 UTC, vaibhav-trq commented on fix-code-0/main.cpp
> +  cout << "Hello World!" << endl;
Add some spacing between here!

2020-05-05 02:20 UTC, vaibhav-trq reviewed
Adding new comments.

2020-05-05 02:20 UTC, vaibhav-trq commented on fix-code-0/main.cpp
> +  cout << "Hello World!" << endl;
Add some spacing between here!

2020-05-05 02:21 UTC, vaibhav-trq reviewed
Adding new comments.

2020-05-05 02:21 UTC, vaibhav-trq commented on fix-code-0/main.cpp
> +  cout << "Hello World!" << endl;
Add some spacing between here!

2020-05-05 02:22 UTC, vaibhav-trq reviewed
Adding new comments.

2020-05-05 02:23 UTC, vaibhav-trq reviewed
Adding new comments.

2020-05-05 02:24 UTC, vaibhav-trq commented on fix-code-0/main.cpp
> +  cout << "Hello World!" << endl;
Fixed.

2020-05-05 04:50 UTC, hellovai requested changes
Please address all of the comments.

2020-05-05 04:50 UTC, hellovai commented on invent-code-0/main.cpp
>  int main() {
Does this comment make it though?

2020-05-05 06:01 UTC, hellovai requested changes
Please address all of the comments.

2020-05-05 06:01 UTC, hellovai commented on fix-code-0/main.cpp
> +  cout << "Hello World!" << endl;
awesome fix!

2020-05-05 06:01 UTC, hellovai commented on fix-code-0/main.cpp
>  }
This isn't very useful...

2020-05-05 06:01 UTC, hellovai commented on invent-code-0/main.cpp
>  int main() {
Yep! Got it on my end :)

2020-05-09 08:49 UTC, vaibhav-trq reviewed
Adding new comments.

2020-05-09 08:50 UTC, vaibhav-trq reviewed
Adding new comments.

2020-05-09 08:52 UTC, vaibhav-trq reviewed
Adding new comments.

2020-05-09 08:52 UTC, vaibhav-trq commented on fix-code-0/main.cpp
>  int main() {
Fixed.

2020-05-11 07:01 UTC, vaibhav-trq reviewed
Adding new comments.

2020-05-11 07:01 UTC, vaibhav-trq commented on fix-code-0/main.cpp
>  int main() {
Fixed.